site_name: BLINK
site_url: https://docs.blink.com/
nav:
    - Home: 
        - About: index.md
        - Installation: installation.md
        - Usage: usage.md
    - API:
        - Apkinfo: apkinfo.md
        - Scanner: scanner.md
        - Detector: detector.md
        - Analysis Scenarios: samples.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
